# Use node_js environnement
language: node_js
node_js:
  - "6"
before_install:
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_45ac9d2588b1_key -iv $encrypted_45ac9d2588b1_iv
  -in client_secret.json.enc -out src/client_secret.json -d
# If the SDK is not already cached, download it and unpack it
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi

- mkdir -p lib
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file src/client_secret.json