language: node_js
node_js:
- lts/*
before_install:
- openssl aes-256-cbc -K $encrypted_45ac9d2588b1_key -iv $encrypted_45ac9d2588b1_iv
  -in client_secret.json.enc -out src/client_secret.json -d
# If the SDK is not already cached, download it and unpack it
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
    export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash;
  fi
- gcloud version
- mkdir -p lib

- gcloud auth activate-service-account --key-file src/client_secret.json